### ISSUE TITLE
Searching with whitespaces

### ISSUE THREAD

**Issue by BigBoyBarney** [hugopl/fzy#7]
Hi!
First of all, thanks a lot for this shard. It's really cool!

I ran into an issue earlier, where searching for a token with a whitespace in a haystack where the given token has no whitespace, results in a complete miss.

```cr
require "fzy"

puts "Searching for 'Something Interesting'"
matches = Fzy.search("Something Interesting", ["SomethingInteresting"])
matches.each do |match|
  puts "value: #{match.item}"
  puts "score: #{match.score}"
  puts "  pos: #{match.positions.inspect}"
end

puts "Searching for 'SomethingInteresting'"
matches = Fzy.search("SomethingInteresting", ["Something Interesting"])
matches.each do |match|
  puts "value: #{match.item}"
  puts "score: #{match.score}"
  puts "  pos: #{match.positions.inspect}"
end
```

this prints
```
Searching for 'Something Interesting'
Searching for 'SomethingInteresting'
value: Something Interesting
score: 19.689999
```

The opposite, however, is not true. Searching for a token *without* whitespace in a haystack where it *has* a whitespace works flawlessly. 

Is there a way around this, or should I remove all whitespaces from the tokens I intend to search for, as that seems to work in both cases?

Thanks in advance!

**Comment by hugopl** [comment]
Just remove the white spaces from the string you search for.

**Simple solution**

```Crystal
"Something Interesting".tr(" ", "")
```

**Another solution**

Write your own match function, fzy search is split in 3 steps:

 1. Filter the collection with all the entries that match the search item, i.e. has all their characters in the same order.
 2. Apply a score for each match.
 3. Sort the collection by score.

So you would need to change the match algorithm to ignore the spaces, the match function that should be monkey patched is here:

https://github.com/hugopl/fzy/blob/1e8afa8da1977e94e727c4d55067eb88145ba655/src/fzy/hay.cr#L26

But a *really* recommend just calling `.tr(" ", "")`.

**Comment by BigBoyBarney** [comment]
Thank you for your detailed answer! I did think that simply removing the whitespaces was the way to go, but it's reassuring having it confirmed.

Thanks a lot! :partying_face:
